[package]
name = "pallet-omnipool-subpools"
version = "1.0.0"
authors = ['GalacticCouncil']
edition = "2021"
license = "Apache-2.0"
homepage = 'https://github.com/galacticcouncil/hydradx-node'
repository = 'https://github.com/galacticcouncil/hydradx-node'
description = "Stableswap subpools support for Omnipool"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# parity
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.1.5" }

# Local
pallet-omnipool = { path = "../omnipool", default-features = false }
pallet-stableswap = { path = "../stableswap", default-features = false }

# primitives
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false }

# FRAME
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false }

# ORML
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.29", default-features = false }

# Warehouse
hydradx-traits = { git = "https://github.com/galacticcouncil/warehouse", rev = "a99b148166ff6cb040233e7f3702979e138dcf20", default-features = false }

# Math
hydra-dx-math = { git = "https://github.com/galacticcouncil/HydraDX-math", rev = "3d74f1c09522e07cc622eb7614a827f3ede1c8ae", default-features = false }

# third party
primitive-types = { version = "0.12.0", default-features = false }

# Optional imports for benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false , optional = true}
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false, optional = true}
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false, optional = true}
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false , optional = true}

[dev-dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false}
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false}
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false}
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false}
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29", default-features = false}
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.29", default-features = false }
pallet-asset-registry = { git = "https://github.com/galacticcouncil/warehouse", rev = "a99b148166ff6cb040233e7f3702979e138dcf20", default-features = false }
proptest = "1.0.0"
pretty_assertions = "1.2.1"
mutagen = {git = "https://github.com/llogiq/mutagen"}
test-case = "2.2.2"

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"pallet-balances/std",
	"orml-tokens/std",
	"pallet-omnipool/std",
	"pallet-stableswap/std",
	"pallet-asset-registry/std",
	"hydra-dx-math/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"sp-core",
	"sp-io",
	"pallet-balances",
]
try-runtime = [ "frame-support/try-runtime" ]
