[patch.crates-io]
frame-benchmarking = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
frame-benchmarking-cli = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
frame-executive = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
frame-support = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
frame-system = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
frame-system-benchmarking = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
frame-system-rpc-runtime-api = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-balances = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-grandpa = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-election-provider-multi-phase = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-randomness-collective-flip = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-sudo = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-timestamp = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-tips = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-transaction-payment-rpc = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-transaction-payment-rpc-runtime-api = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-basic-authorship = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-chain-spec = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-cli = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-client-api = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-client-db = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-consensus = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-consensus-epochs = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-executor = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-finality-grandpa = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-informant = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-keystore = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-network = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-offchain = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-rpc = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-rpc-api = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-service = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-telemetry = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-transaction-pool = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-api = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-application-crypto = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-arithmetic = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-block-builder = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-blockchain = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-consensus = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-core = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-externalities = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-finality-grandpa = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-inherents = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-io = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-offchain = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-rpc = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-runtime = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-runtime-interface = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-session = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-staking = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-state-machine = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-std = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-storage = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-timestamp = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-tracing = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-transaction-pool = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-trie = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-version = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
substrate-frame-rpc-system = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}

pallet-transaction-payment = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}

#staking
pallet-authority-discovery = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-authorship = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-babe = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-collective = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-elections-phragmen = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-im-online = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-offences = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-session = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-staking = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-staking-reward-curve = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
pallet-treasury = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-authority-discovery = {git = "https://github.com/paritytech/substrate.git", rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-consensus-babe = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-consensus-babe-rpc = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sc-consensus-slots = {git = "https://github.com/paritytech/substrate.git", rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-authority-discovery = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-consensus-babe = {git = 'https://github.com/paritytech/substrate', rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}
sp-keystore = {git = "https://github.com/paritytech/substrate.git", rev = '4b5b9bdafb9adfc7e3f740c515b5359201d32d84'}

# ORML dependencies
orml-currencies = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master'}
orml-tokens = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master'}
orml-traits = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master'}
orml-utilities = {git = 'https://github.com/open-web3-stack/open-runtime-module-library', branch = 'master'}

librocksdb-sys = {git = "https://github.com/hdevalence/rust-rocksdb", branch = "master"}

[profile.release]
panic = 'unwind'

[workspace]
members = [
  # 'pallets/proposal', Update this
  'node',
  'pallets/amm',
  'pallets/asset-registry',
  'pallets/exchange',
  'pallets/transaction-multi-payment',
  'primitives',
  'runtime',
]
