[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'runtime/common',
  'runtime/hydradx',
  'runtime/testing-hydradx',
  'primitives',
  'utils/build-script-utils'
]

[patch."https://github.com/galacticcouncil/warehouse"]
hydradx-traits = { git = "https://github.com/galacticcouncil//warehouse", branch = "polkadot-v0.9.16"}