[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'pallets/omnipool',
  'runtime/common',
  'runtime/hydradx',
  'runtime/testing-hydradx',
  'primitives',
  'utils/build-script-utils',
  'integration-tests',
]
