[patch.crates-io]
frame-benchmarking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
frame-benchmarking-cli = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
frame-executive = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
frame-support = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
frame-system = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
frame-system-benchmarking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
frame-system-rpc-runtime-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-balances = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-democracy = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-election-provider-multi-phase = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-grandpa = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-identity = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-randomness-collective-flip = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-scheduler = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-sudo = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-timestamp = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-tips = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-transaction-payment-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-transaction-payment-rpc-runtime-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-basic-authorship = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-chain-spec = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-cli = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-client-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-client-db = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-consensus = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-consensus-epochs = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-executor = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-finality-grandpa = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-informant = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-keystore = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-network = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-offchain = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-rpc-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-service = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-telemetry = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-transaction-pool = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-api = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-application-crypto = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-arithmetic = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-block-builder = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-blockchain = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-consensus = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-core = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-externalities = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-finality-grandpa = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-inherents = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-io = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-offchain = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-runtime = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-runtime-interface = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-session = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-staking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-state-machine = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-std = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-storage = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-timestamp = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-tracing = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-transaction-pool = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-trie = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-version = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-npos-elections = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
substrate-frame-rpc-system = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}

pallet-transaction-payment = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}

#staking
pallet-authority-discovery = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-authorship = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-babe = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-collective = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-elections-phragmen = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-im-online = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-offences = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-session = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-staking = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-staking-reward-curve = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-treasury = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
pallet-utility = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-authority-discovery = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.8'}
sc-consensus-babe = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-consensus-babe-rpc = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sc-consensus-slots = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.8'}
sc-consensus-uncles = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.8'}
sp-authority-discovery = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-consensus-babe = {git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.8'}
sp-keystore = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.8'}
sp-authorship = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.8'}
max-encoded-len = {git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.8'}

# ORML dependencies
orml-currencies = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '33d9ac0927ba61e15763ee438721ef92d408271a' }
orml-tokens = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '33d9ac0927ba61e15763ee438721ef92d408271a' }
orml-traits = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '33d9ac0927ba61e15763ee438721ef92d408271a' }
orml-utilities = { git = 'https://github.com/open-web3-stack/open-runtime-module-library', rev = '33d9ac0927ba61e15763ee438721ef92d408271a' }

# Hydra pallets - from Basilisk repo
pallet-asset-registry = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
#pallet-asset-registry = { path = '../Basilisk-node/pallets/asset-registry' }
pallet-exchange = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
pallet-exchange-benchmarking = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
pallet-transaction-multi-payment = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
pallet-multi-payment-benchmarking = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
pallet-xyk= { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
pallet-xyk-rpc = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
pallet-xyk-rpc-runtime-api = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }
primitives = { git = 'https://github.com/galacticcouncil/Basilisk-node', rev = '3663055f5c651c6cae9413b43231a082a78d2aa4' }

[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'runtime/common',
  'runtime/hydra-dx',
  'runtime/testing-hydra-dx',
  'pallets/genesis-history',
  'utils/build-script-utils'
]
