[profile.release]
panic = 'unwind'

[workspace]
members = [
  'node',
  'runtime/common',
  'runtime/hydra-dx',
  'runtime/testing-hydra-dx',
  'pallets/asset-registry',
  'pallets/exchange',
  'pallets/genesis-history',
  'pallets/xyk',
  'primitives',
  'utils/build-script-utils'
]


[patch."https://github.com/galacticcouncil/warehouse"]
pallet-transaction-multi-payment = { git = "https://github.com/galacticcouncil//warehouse", rev = "aef26bc6baf9020910b86f63019ae966a4ebcdb2"}
pallet-faucet= { git = "https://github.com/galacticcouncil//warehouse", rev = "aef26bc6baf9020910b86f63019ae966a4ebcdb2"}
hydradx-traits = { git = "https://github.com/galacticcouncil//warehouse", rev = "aef26bc6baf9020910b86f63019ae966a4ebcdb2"}