[package]
name = 'pallet-price-oracle'
version = '0.3.3'
description = 'Price oracle for AMM pools'
authors = ['GalacticCouncil']
edition = '2021'
license = 'Apache 2.0'
repository = 'https://github.com/galacticcouncil/warehouse'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.4.0" }
serde = {features = ['derive'], optional = true, version = '1.0.137'}
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }

# HydraDX dependencies
hydradx-traits = { workspace = true }

# Substrate dependencies
frame-benchmarking = { workspace = true, optional = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
sp-core = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
sp-io = { workspace = true }
test-utils = { workspace = true }

[features]
default = ['std']
runtime-benchmarks = [
  "frame-benchmarking/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "frame-support/runtime-benchmarks",
]
std = [
  'serde',
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'frame-benchmarking/std',
  'sp-core/std',
  'sp-std/std',
  'hydradx-traits/std',
  'scale-info/std',
]
