[package]
name = "testing-hydradx-runtime"
version = "159.0.0"
authors = ["GalacticCouncil"]
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/HydraDX-node"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
substrate-build-script-utils = { workspace = true }
substrate-wasm-builder = { workspace = true }

[dependencies]
hex-literal = "0.3.4"
serde = { features = ["derive"], optional = true, version = "1.0.136" }
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
smallvec = "1.9.0"

# local dependencies
primitives = { workspace = true }
common-runtime = { workspace = true }
pallet-claims = { workspace = true }
pallet-genesis-history = { workspace = true }
pallet-omnipool = { workspace = true }
pallet-circuit-breaker = { workspace = true }
pallet-omnipool-liquidity-mining = { workspace = true }
pallet-dca =  { workspace = true }

# pallets
pallet-balances = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury = { workspace = true }
pallet-utility = { workspace = true }
pallet-aura = { workspace = true }
pallet-session = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-preimage = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-identity = { workspace = true }
pallet-collective = { workspace = true }
pallet-tips = { workspace = true }
pallet-proxy = { workspace = true }
pallet-multisig = { workspace = true }
pallet-democracy = { workspace = true }
pallet-elections-phragmen = { workspace = true }
pallet-uniques = { workspace = true }

# Warehouse dependencies
hydradx-adapters = { workspace = true }
hydradx-traits = { workspace = true }
pallet-relaychain-info = { workspace = true }
pallet-transaction-multi-payment = { workspace = true }
pallet-asset-registry = { workspace = true }
pallet-collator-rewards = { workspace = true }
pallet-currencies = { workspace = true }
pallet-ema-oracle = { workspace = true }
pallet-transaction-pause = { workspace = true }
pallet-duster = { workspace = true }
warehouse-liquidity-mining = { workspace = true }
pallet-otc = { workspace = true }
pallet-route-executor =  {workspace = true }

# ORML dependencies
orml-tokens = { workspace = true }
orml-traits = { workspace = true }
orml-vesting = { workspace = true }
orml-benchmarking = { workspace = true, optional = true }

# orml XCM support
orml-xtokens = { workspace = true }
orml-xcm-support = { workspace = true }
orml-unknown-tokens = { workspace = true }
orml-xcm = { workspace = true }

# collator support
pallet-collator-selection = { workspace = true }
pallet-authorship = { workspace = true }

# Cumulus dependencies
cumulus-pallet-aura-ext = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }
cumulus-pallet-xcm = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-pallet-dmp-queue = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-primitives-utility = { workspace = true }
cumulus-primitives-parachain-inherent = { workspace = true }
cumulus-primitives-timestamp = { workspace = true }
parachain-info = { workspace = true }

# Polkadot dependencies
polkadot-parachain = { workspace = true, features = ["wasm-api"] }
pallet-xcm = { workspace = true }
polkadot-xcm = { workspace = true }
xcm-executor = { workspace = true }
xcm-builder = { workspace = true }

# Substrate dependencies
frame-benchmarking = { workspace = true, optional = true }
frame-executive = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-benchmarking = { workspace = true, optional = true }
frame-system-rpc-runtime-api = { workspace = true }
frame-try-runtime = { workspace = true, optional = true }
sp-api = { workspace = true }
sp-block-builder = { workspace = true }
sp-consensus-aura = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-externalities = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-session = { workspace = true }
sp-std = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-version = { workspace = true }
sp-trie = { workspace = true }
sp-io = { workspace = true }

[features]
default = ["std"]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system-benchmarking/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "orml-benchmarking",
    "pallet-xcm/runtime-benchmarks",#
    "xcm-builder/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-collator-selection/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "pallet-treasury/runtime-benchmarks",
    "pallet-preimage/runtime-benchmarks",
    "pallet-scheduler/runtime-benchmarks",
    "pallet-claims/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "pallet-collective/runtime-benchmarks",
    "pallet-tips/runtime-benchmarks",
    "pallet-proxy/runtime-benchmarks",
    "pallet-multisig/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-democracy/runtime-benchmarks",
    "pallet-asset-registry/runtime-benchmarks",
    "pallet-xcm/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "pallet-uniques/runtime-benchmarks",
    "pallet-route-executor/runtime-benchmarks"
]
std = [
    "codec/std",
    "serde",
    "scale-info/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "frame-try-runtime/std",
    "common-runtime/std",
    "cumulus-pallet-parachain-system/std",
    "cumulus-pallet-aura-ext/std",
    "cumulus-primitives-core/std",
    "cumulus-pallet-xcm/std",
    "cumulus-pallet-xcmp-queue/std",
    "parachain-info/std",
    "pallet-xcm/std",
    "polkadot-xcm/std",
    "xcm-executor/std",
    "xcm-builder/std",
    "orml-tokens/std",
    "orml-traits/std",
    "orml-vesting/std",
    "orml-xtokens/std",
    "orml-xcm-support/std",
    "orml-xcm/std",
    "orml-unknown-tokens/std",
    "orml-benchmarking/std",
    "pallet-aura/std",
    "pallet-balances/std",
    "pallet-session/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-preimage/std",
    "pallet-scheduler/std",
    "pallet-identity/std",
    "pallet-collective/std",
    "pallet-tips/std",
    "pallet-proxy/std",
    "pallet-multisig/std",
    "pallet-transaction-payment/std",
    "pallet-transaction-payment-rpc-runtime-api/std",
    "pallet-democracy/std",
    "pallet-elections-phragmen/std",
    "pallet-claims/std",
    "pallet-treasury/std",
    "pallet-collator-selection/std",
    "pallet-authorship/std",
    "pallet-utility/std",
    "pallet-uniques/std",
    "pallet-currencies/std",
    "pallet-ema-oracle/std",
    "pallet-transaction-pause/std",
    "pallet-route-executor/std",
    "hydradx-traits/std",
    "pallet-transaction-multi-payment/std",
    "pallet-genesis-history/std",
    "pallet-asset-registry/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-consensus-aura/std",
    "sp-core/std",
    "sp-io/std",
    "sp-inherents/std",
    "sp-externalities/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-std/std",
    "sp-trie/std",
    "sp-transaction-pool/std",
    "sp-version/std",
    "pallet-duster/std",
    "warehouse-liquidity-mining/std",
    "pallet-omnipool-liquidity-mining/std",
]
