[package]
name = "pallet-currencies-rpc-runtime-api"
version = "1.0.0"
description = "Currencies runtime api"
authors = ["GalacticCouncil"]
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/hydration-node"

[dependencies]
sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "sp-runtime/std",
    "sp-api/std",
    "sp-std/std",
    "sp-core/std",
]
