[package]
authors = ['GalacticCouncil']
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydradx-node'
license = 'Apache 2.0'
name = 'common-runtime'
repository = 'https://github.com/galacticcouncil/hydradx-node'
version = '23.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
wasm-builder-runner = {package = 'substrate-wasm-builder-runner', version = '1.0.5'}

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
primitives = {path = '../../primitives', default-features = false}

# Substrate dependencies
frame-support = {default-features = false, version = '3.0.0'}
frame-system = {default-features = false, version = '3.0.0'}
pallet-collective = {default-features = false, version = '3.0.0'}
pallet-transaction-payment = {default-features = false, version = '3.0.0'}
sp-core = {default-features = false, version = '3.0.0'}
sp-npos-elections = {version = '3.0.0', default-features = false}
sp-runtime = {default-features = false, version = '3.0.0'}
