[package]
name = "common-runtime"
version = "102.3.12"
authors = ["GalacticCouncil"]
edition = "2021"
license = "Apache 2.0"
repository = "https://github.com/galacticcouncil/HydraDX-node"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-wasm-builder = { workspace = true }

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
primitives = { workspace = true }
primitive-types = {default-features = false, version = '0.12.0'}

pallet-omnipool = { workspace = true }
pallet-circuit-breaker = { workspace = true }
pallet-omnipool-liquidity-mining = { workspace = true }
pallet-claims = { workspace = true }
pallet-dca = { workspace = true }

hydra-dx-math = { workspace = true }

# Warehouse dependencies
hydradx-traits = { workspace = true }
pallet-transaction-multi-payment = { workspace = true }
pallet-asset-registry = { workspace = true }
pallet-currencies = { workspace = true }
pallet-transaction-pause = { workspace = true }
pallet-otc = { workspace = true }
pallet-ema-oracle = { workspace = true }
warehouse-liquidity-mining = { workspace = true }
pallet-route-executor = { workspace = true }
pallet-duster = { workspace = true }
pallet-staking = { workspace = true }

# Substrate dependencies
sp-runtime = { workspace = true }
sp-core = { workspace = true }
sp-std = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
sp-npos-elections = { workspace = true }
pallet-transaction-payment = { workspace = true }
pallet-collective = { workspace = true }
pallet-treasury = { workspace = true }
pallet-utility = { workspace = true }
pallet-democracy = { workspace = true }
pallet-identity = { workspace = true }
pallet-preimage = { workspace = true }
pallet-proxy = { workspace = true }
pallet-scheduler = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-balances = { workspace = true }
pallet-tips = { workspace = true }

# Polkadot dependencies
pallet-xcm = { workspace = true }

# ORML dependencies
orml-tokens = { workspace = true }
orml-vesting = { workspace = true }
orml-traits = { workspace = true }
orml-xcm-support = { workspace = true }

# Cumulus dependencies
pallet-collator-selection = { workspace = true }
cumulus-pallet-xcmp-queue = { workspace = true }
cumulus-primitives-core = { workspace = true }
cumulus-pallet-parachain-system = { workspace = true }

# Polkadot dependencies
xcm = { workspace = true }
xcm-executor = { workspace = true }

[features]
default = ["std"]

std = [
    "scale-info/std",
    "primitives/std",
    "pallet-omnipool/std",
    "sp-runtime/std",
    "sp-core/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "sp-npos-elections/std",
    "pallet-transaction-multi-payment/std",
    "pallet-collective/std",
    "pallet-treasury/std",
    "pallet-utility/std",
    "pallet-democracy/std",
    "pallet-identity/std",
    "pallet-preimage/std",
    "pallet-proxy/std",
    "pallet-route-executor/std",
    "pallet-scheduler/std",
    "pallet-timestamp/std",
    "pallet-balances/std",
    "pallet-claims/std",
    "pallet-transaction-multi-payment/std",
    "pallet-asset-registry/std",
    "pallet-currencies/std",
    "pallet-transaction-pause/std",
    "orml-tokens/std",
    "orml-vesting/std",
    "orml-traits/std",
    "orml-xcm-support/std",
    "pallet-collator-selection/std",
    "cumulus-pallet-xcmp-queue/std",
    "xcm/std",
    "xcm-executor/std",
]
