[package]
name = "pallet-staking-runtime-api"
version = "0.1.0"
authors = ['GalacticCouncil']
edition = "2021"
license = "Apache-2.0"

[dependencies]
sp-runtime = { workspace = true}
sp-api = { workspace = true}
sp-std = { workspace = true}
sp-core = { workspace = true}

[features]
default = ["std"]
std = [
	"sp-runtime/std",
	"sp-api/std",
	"sp-std/std",
	"sp-core/std",
]