[package]
name = "omnix-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hydra-dx-math = { workspace =  true}
pallet-omnix = { workspace = true}
pallet-omnipool = { workspace = true}
sp-std = {workspace = true}
sp-runtime = {workspace = true}


[features]
default = ["std"]
std = [
    "hydra-dx-math/std",
    "pallet-omnix/std",
    "sp-std/std",
    "pallet-omnipool/std",
    "sp-runtime/std",
]