[package]
name = 'pallet-dca'
version = '1.0.0'
description = 'A pallet to manage DCA scheduling'
authors = ['GalacticCouncil']
edition = '2021'
license = 'Apache 2.0'
repository = "https://github.com/galacticcouncil/warehouse/tree/master/route-executor"

[dependencies]

log = { version = "0.4.17", default-features = false }
rand = { version = "0.8.4", default-features = false }

# parity
scale-info = { version = "2.3.1", default-features = false, features = ["derive"] }
codec = { default-features = false, features = ["derive"], package = "parity-scale-codec", version = "3.4.0" }

# primitives
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }

# FRAME
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }

# HydraDX dependencies
pallet-omnipool = { path="../omnipool", default-features = false }
pallet-circuit-breaker = { path="../circuit-breaker", default-features = false }
hydradx-traits = { git = "https://github.com/galacticcouncil/warehouse", rev = "739cd4298bd62bf4f0a6416e2c7502d889b24fb0", default-features = false }
hydradx-adapters = { git = "https://github.com/galacticcouncil/warehouse", rev = "739cd4298bd62bf4f0a6416e2c7502d889b24fb0", default-features = false }
pallet-relaychain-info = { git = "https://github.com/galacticcouncil/warehouse", rev = "739cd4298bd62bf4f0a6416e2c7502d889b24fb0", default-features = false }
pallet-ema-oracle =  { git = "https://github.com/galacticcouncil/warehouse", rev = "739cd4298bd62bf4f0a6416e2c7502d889b24fb0", default-features = false }
pallet-route-executor =  { git = "https://github.com/galacticcouncil/warehouse", rev = "739cd4298bd62bf4f0a6416e2c7502d889b24fb0", default-features = false }

hydra-dx-math = { git = "https://github.com/galacticcouncil/HydraDX-math", rev = "35e5c0775a07e057ed5247ba96dfa254d691f034", default-features = false }

# ORML dependencies
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.38", default-features = false }

# Optional imports for benchmarking
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false , optional = true}
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false , optional = true}
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false, optional = true}
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false , optional = true}

primitives = { path="../../primitives", default-features = false }


[dev-dependencies]
smallvec = "1.9.0"
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
pallet-currencies = { git = "https://github.com/galacticcouncil/warehouse", rev = "739cd4298bd62bf4f0a6416e2c7502d889b24fb0", default-features = false }
lazy_static = { features = ["spin_no_std"], version = "1.4.0", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false }
sp-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.38", default-features = false}
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", branch = "polkadot-v0.9.38", default-features = false, features=["std"]}
proptest = "1.0.0"
pretty_assertions = "1.2.1"
test-utils = { git = "https://github.com/galacticcouncil/warehouse", rev = "739cd4298bd62bf4f0a6416e2c7502d889b24fb0", default-features = false }
test-case = "2.2.2"
primitive-types = { version = "0.12.0", default-features = false }

[features]
default = ['std']
std = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-runtime/std',
  'sp-std/std',
  'sp-core/std',
  'sp-io/std',
  "scale-info/std",
  "orml-tokens/std",
  "hydradx-traits/std",
  "hydradx-adapters/std",
  "pallet-relaychain-info/std",
  "orml-tokens/std",
  "pallet-omnipool/std",
  "pallet-ema-oracle/std",
  "pallet-circuit-breaker/std",
  "pallet-route-executor/std",
]

runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
