[package]
authors = ['GalacticCouncil']
build = 'build.rs'
description = 'Hydra DX'
edition = '2018'
homepage = 'https://github.com/galacticcouncil/hydradx-node'
license = 'Apache 2.0'
name = 'hydra-dx'
repository = 'https://github.com/galacticcouncil/hydradx-node'
version = '6.2.0'

[[bin]]
name = 'hydra-dx'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
hydra-dx-build-script-utils = {path = '../utils/build-script-utils'}

[dependencies]
jsonrpc-core = '18.0.0'
serde_json = "1.0.61"
structopt = '0.3.8'
futures = '0.3.4'
hex-literal = "0.3.1"

# local dependencies
common-runtime = {path = '../runtime/common'}
hydra-dx-runtime = {path = '../runtime/hydra-dx'}
testing-hydra-dx-runtime = {path = '../runtime/testing-hydra-dx'}
pallet-xyk-rpc = {path = '../pallets/xyk/rpc'}
pallet-xyk-rpc-runtime-api = {path = '../pallets/xyk/rpc/runtime-api', default-features = false}
primitives = {path = '../primitives'}

# Substrate dependencies
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", optional = true }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-authority-discovery= { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", features = ["wasmtime"] }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-client-db = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-consensus-epochs= { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", features = ["wasmtime"] }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", features = ["wasmtime"] }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
pallet-im-online= { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
pallet-staking= { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
sp-authorship= { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15" }
frame-try-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", optional = true }
try-runtime-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.15", optional = true }

[features]
default = [
  "frame-benchmarking-cli",
]
runtime-benchmarks = [
  'hydra-dx-runtime/runtime-benchmarks',
  'testing-hydra-dx-runtime/runtime-benchmarks',
  "frame-benchmarking-cli",
]
