name: docker release

on:
  push:
    branches:
      - master
      - stable
      - docker-release
    tags:

  docker-build:
    runs-on: docker
    needs: pop-runner-instance
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: docker.pkg.github.com/galacticcouncil/hydradx-node/hydra-dx:${{ steps.extract_branch.outputs.branch }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
