name: docker

on:
  push:
    branches:
      - master
      - stable
      - docker-release
    tags:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/galacticcouncil/hydradx-node/hydra-dx:${{ github.ref }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
