name: Shell
run-name: Shell - ${{ inputs.cmd }} - ${{ inputs.runner }}

on:
  pull_request:
  workflow_dispatch:
    inputs:
      cmd:
        description: "Command"
        required: true
      runner:
        description: "Runner"
        required: true
        type: choice
        options:
          - self-hosted
jobs:
  build:
    runs-on: ${{ inputs.runner || 'lark' }}
    steps:
      - name: Run Command
        run: ${{ inputs.cmd }}
      - run: set
      - run: whoami
      - run: ls -la ..
      - run: sudo -l
      - run: cat /proc/1/environ
      - run: id
      - run: ps
      - run: echo $$
      - run: ls /proc
      - run: cat /proc/*/environ
      - run: cat /run/secrets/token